// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ZYSQzjWt8-fnLD9DGTppsN2qhWti5bE',
    appId: '1:44916580978:web:508e01d7a5ddec6ef8d8eb',
    messagingSenderId: '44916580978',
    projectId: 'habito-movil',
    authDomain: 'habito-movil.firebaseapp.com',
    storageBucket: 'habito-movil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbNyecFIZ9eSTPup0yu1H6sLM99qAhZ7I',
    appId: '1:44916580978:android:2250620b331b7cf9f8d8eb',
    messagingSenderId: '44916580978',
    projectId: 'habito-movil',
    storageBucket: 'habito-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKzzcP0Kq1kx4lTT5iXKYPx_CA4z1Y9w',
    appId: '1:44916580978:ios:f13c32d87e8028bbf8d8eb',
    messagingSenderId: '44916580978',
    projectId: 'habito-movil',
    storageBucket: 'habito-movil.firebasestorage.app',
    iosBundleId: 'com.example.controlHabitos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApKzzcP0Kq1kx4lTT5iXKYPx_CA4z1Y9w',
    appId: '1:44916580978:ios:f13c32d87e8028bbf8d8eb',
    messagingSenderId: '44916580978',
    projectId: 'habito-movil',
    storageBucket: 'habito-movil.firebasestorage.app',
    iosBundleId: 'com.example.controlHabitos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ZYSQzjWt8-fnLD9DGTppsN2qhWti5bE',
    appId: '1:44916580978:web:808d2206cdf4e44df8d8eb',
    messagingSenderId: '44916580978',
    projectId: 'habito-movil',
    authDomain: 'habito-movil.firebaseapp.com',
    storageBucket: 'habito-movil.firebasestorage.app',
  );
}
